### PR TITLE
rebasing system-with-data onto main

### PR DESCRIPTION
**Pull request by liam-o-marsh**
----
📚 Documentation preview 📚: https://rascaline--339.org.readthedocs.build/en/339/

### CODE REVIEW

**Comment by liam-o-marsh** [comment]
honestly having this be a merge proper is a bad idea, since my version is already a rebase
it is probably better to resolve this out-of-band, if you have the time for it
or not at all, if you don't want to merge system-with-data into main without my bond-centered stuff to use it

**Comment by Luthaf** [comment]
I can do a quick rebase of this branch! For the bond-centered descriptor, I am finally able to spend some time working on rascaline, so after #328 is merged my next priority will be making a proper release of the code (#284). At the same time/after this, we could try again to update the bond-centered descriptor to the new hyper schema & merge it. 

Since the last time we chatted about it, was this descriptor used in a scientific paper? It would push it a couple of steps up in my TODO list!

**Comment by Luthaf** [comment]
Ok, the branch has been rebased, and also includes #338.

**Comment by liam-o-marsh** [comment]
thanks!

> At the same time/after this, we could try again to update the bond-centered descriptor to the new hyper schema & merge it.  
> Since the last time we chatted about it, was this descriptor used in a scientific paper? It would push it a couple of steps up in my TODO list!

Definitely later, that project became too big to be a single publication, and somehow actual bond-centered descriptions are way up in the dependency chain between papers
The main reason why I'm looking at rascaline again is because Joe told me about a bunch of changes that would be interesting, so I'm trying to slowly rebase my copy of it (which has a bunch of changes, both unmerged and not upstreamed at all)

**Pull request closed without merging**
