### PR TITLE
Read the docs deploy

### LINKED ISSUE #101: Generate docs of PRs
When working with the reviewing docs it is very useful to the see the rendered results without checking out the changed locally. Read the doc allows such an option. [They can build the docs for each PR](https://docs.readthedocs.io/en/stable/pull-requests.html). The results are integrated in the Build status report of each PR.

We should add this functionality here and later also to other projects.

### PR DESCRIPTION
**Pull request by PicoCentauri**
Closes #101

### CODE REVIEW

**Comment by PicoCentauri** [comment]
I pleased the CI gods and the latest builds are [working](https://readthedocs.org/projects/rascaline/builds/18086977/).

**Comment by Luthaf** [comment]
Looks nice! Is there a way to only build with rtd for pull requests (and leave the main docs on github pages)? And is there a way to post a message to the PR with a link to the documentation instead of having to know it exists?

**Comment by PicoCentauri** [comment]
> Looks nice! Is there a way to only build with rtd for pull requests (and leave the main docs on github pages)? 

The main docs are stilled deployed by GH-pages. RTD is building the docs for the master branch as well. You can not disable this afaik. However, this is not so bad. We can should keep the RTD master build as a 'hidden' docs backup in case GH-pages is down or unavailable at some point.

> And is there a way to post a message to the PR with a link to the documentation instead of having to know it exists?

The results of the docs build are already integrated in the conversation and appear where the tests are. When the build is successful and you click on the `details` link you will be directed to the RDT version of the docs. If the build fails you will be redirected to the log. This is already quite handy and I think there is no need for an additional link to post.

**Comment by Luthaf** [comment]
> We can should keep the RTD master build as a 'hidden' docs backup in case GH-pages is down or unavailable at some point.

I'm mostly concerned about SEO here: for search engines to direct to the right docs, you need to have a single version of them online. When you say "hidden", is there a way to make it not show up in google searches at all?

**Comment by PicoCentauri** [comment]
Let me check if there is a privacy option.

**Comment by Luthaf** [comment]
Ok, I got redirect to work, so that https://rascaline.readthedocs.io/en/latest/ redirects to the github pages, while the PR documentations stays at RTD.

**Pull request merged**
