### PR TITLE
Added cg_utils to Rascaline

### PR DESCRIPTION
**Pull request by ecignoni**
----
:books: Documentation preview :books:: https://rascaline--185.org.readthedocs.build/en/185/

### CODE REVIEW

**Comment by Luthaf** [comment]
This is missing a test to ensure the code actually does what we think it do!

**Comment by Luthaf** [comment]
Linter is not happy, you can run it locally with `tox -e lint` and fix most of the issues with `tox -e format`

**Comment by agoscinski** [comment]
Writing down TODOs because I will probably not touch it for a week

TODOs for this PR:
- decouple(couple(X)) propto X
- compute SOAP and compare with spherical expansion + CG utils
- regression test
- refactor a bit
- remove nonzero mask
- add code documentation from Edoardo's code [cgreal.zip](https://github.com/Luthaf/rascaline/files/11625787/cgreal.zip)
- sync with documtenation in PR #184 

TODOs in following PRs:
- add equistore block support https://github.com/lab-cosmo/equistore-examples/blob/restructured-pytorch-hamiltonian/torch_hamiltonian_utils/torch_ham.py
- add torch support
- think about support of n-centers representations with this (imn, ijm'n' -> ijµnn' is one of them, but there are a lot of variations)

**Comment by agoscinski** [comment]
So there is a more documented version in librascal https://github.com/lab-cosmo/librascal/blob/master/bindings/rascal/utils/cg_utils.py Also with two very good notebook examples. `nice_demo` and `equivariant_demo`.  I will try to merge these two into the current version.

I still need more time to understand the code, its quite complicated. I think we can completely get rid of this `combinations_string` by enforcing an order of the dimension in the array. The flexibility by the argument makes it harder to understand and to use. From the examples I cannot really gather a real advantage for this flexibility.

**Comment by Luthaf** [comment]
Closing in favor of #237

**Pull request closed without merging**
